# Site settings 配置站点
title: 'Lewin的个人博客'
description: 'Go straight'
keywords: ''
url: 'https://saodd.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: 'Lewin'
NickName: 'Lewin'
webtitle: 'Lewin的个人博客'
bio: '不想写前端的数据库不是一个好的后端'
about: true
aboutyou: '
 -- 毕业于某985统招本科工程专业，金融双学位；工作3年后毅然放弃在银行给处长厅长写材料的"铁饭碗"，
投身于IT行业。只为追求儿时梦想。<br>
 -- 目前就职于：深圳 · 某私募基金公司<br>
 -- 主要技能：Python数据分析，自动化工具，Web后端开发<br>
 -- 次要技能：数据库，Web前端，Docker<br>
 -- 学习方向：Golang，算法与数据结构，计算机基础<br>
 -- 其他技能：CET6/TOFEL全英文工作能力，证券/期货/基金从业资格
'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'mailto:lewinlan@dingtalk.com'
  # weixin: '' # 你的微信二维码存放的地址
  # qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/Saodd'
  # Codepen: ''
  # weibo: ''
  # instagram: ''
  # Twitter: ''
  # Dribbble: ''
  # Facebook: ''
  # Google: ''
  # zhihu: ''
  # juejin: ''
  # twitch: ''

# 分页
paginate: 10
paginatepath: ['page:num']

# since
footer:
  since: 2019

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  Lewin的官方网站: "http://49.234.46.113:8080/"
  #'https://www.lewinblog.com/'
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: false
livere_uid: '' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: '68fec820aca6e115d9a1740c0130b9aa'
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: true
google-ID: 'UA-143522748-1'

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
